modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/The-Acronym-Coders/epos/issues"

[[mods]]
    modId="epos-api"
    version="${file.jarVersion}"
    displayName="Epos-API"
    authors="SkySom, Lanse505, pupnewfster"
    description='''
Adds Classes, Skills, and Leveling to Minecraft.
    Credits to:
        - Alexander for the Level-Up sound!
            - http://www.orangefreesounds.com/level-sound-effect/
        - HRZNStudio & The Titanium Team
            - For the great work done with the Titanium API
'''